### ISSUE TITLE
无法使用HUD状态显示

### ISSUE THREAD

**Issue by SteveCodeFox** [RealHeart/ZMusic-Mod#7]
服务端的ZMusic可以把信息发给装有AllMusicMod的mc客户端上
![image](https://github.com/RealHeart/ZMusic-Mod/assets/85626499/8fa6bc60-1d7a-4301-9881-cbcf64412da7)
![image](https://github.com/RealHeart/ZMusic-Mod/assets/85626499/774ba5d2-f2db-4270-8fc2-77afa6486e58)
但是实测装ZMusic Mod的客户端没有任何信息显示
![image](https://github.com/RealHeart/ZMusic-Mod/assets/85626499/f07b76fd-2b86-4c32-ad5f-7ba77db6e414)

**Comment by RealHeart** [comment]
ZMusic Mod 暂不支持 Hud 功能
